export const personData = [
  {
    firstname: "Daniel",
    lastname: "Zurfluh",
    primaryFunction: "Soldat",
    secondaryFunctions: "Technischer Zug, Korpsmotorfahrer, FUST",
    joined: "1995",
    imagePath: "/images/persons/daniel-zurfluh.webp",
  },
  {
    firstname: "Michael",
    lastname: "Piffner",
    primaryFunction: "Soldat",
    secondaryFunctions: "Seedienst",
    joined: "2009",
    imagePath: "/images/persons/michael-pfiffner.webp",
  },
  {
    firstname: "Roman",
    lastname: "Jenny",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Chemiewehr, Motorfahrer, Seedienst",
    joined: "2009",
    imagePath: "/images/persons/roman-jenny.webp",
  },
  {
    firstname: "Michael",
    lastname: "Limacher",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Seedienst",
    joined: "2009",
    imagePath: "/images/persons/michael-limacher.webp",
  },
  {
    firstname: "Marco",
    lastname: "Bieri",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz",
    joined: "2012",
    imagePath: "/images/persons/marco-bieri.webp",
  },
  {
    firstname: "Markus",
    lastname: "Skupch",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Chemiewehr",
    joined: "2015",
    imagePath: "/images/persons/markus-skupch.webp",
  },
  {
    firstname: "Benedikt",
    lastname: "Bitzi",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Motorfahrer",
    joined: "2013",
    imagePath: "/images/persons/benedikt-bitzi.webp",
  },
  {
    firstname: "Andreas",
    lastname: "Christen",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Chemiewehr, Verkehrsdienst",
    joined: "2013",
    imagePath: "/images/persons/andreas-christen.webp",
  },
  {
    firstname: "Manfred",
    lastname: "Wälchli",
    primaryFunction: "Soldat",
    secondaryFunctions: "FUST",
    joined: "2015",
    imagePath: "/images/persons/manfred-waelchlin.webp",
  },
  {
    firstname: "Danny",
    lastname: "Wiener",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Chemiewehr, Jugendfeuerwehr Kader",
    joined: "2016",
    imagePath: "/images/persons/danny-wiener.webp",
  },
  {
    firstname: "Sascha",
    lastname: "Hofer",
    primaryFunction: "Freimitglied",
    secondaryFunctions: "-",
    joined: "2020",
    imagePath: "/images/persons/sascha-hofer.webp",
  },
  {
    firstname: "Ralf",
    lastname: "Bundi",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Technischer Zug, Motorfahrer",
    joined: "2020",
    imagePath: "/images/persons/ralf-bundi.webp",
  },
  {
    firstname: "Carlo",
    lastname: "Real",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Technischer Zug, Betreuung",
    joined: "2021",
    imagePath: "/images/persons/carlo-real.webp",
  },
  {
    firstname: "Rahel",
    lastname: "Bürgi",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Motorfahrer",
    joined: "2021",
    imagePath: "/images/persons/rahel-buergi.webp",
  },
  {
    firstname: "Eveline",
    lastname: "Meister",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz",
    joined: "2021",
    imagePath: "/images/persons/eveline-meister.webp",
  },
  {
    firstname: "Peter",
    lastname: "Ernst",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz, Motorfahrer",
    joined: "2021",
    imagePath: "/images/persons/peter-ernst.webp",
  },
  {
    firstname: "Thomas",
    lastname: "Glauser",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz",
    joined: "2022",
    imagePath: "/images/persons/thomas-glauser.webp",
  },
  {
    firstname: "Annika",
    lastname: "Christen",
    primaryFunction: "Soldat",
    secondaryFunctions: "Atemschutz",
    joined: "2022",
    imagePath: "/images/persons/annika-christen.webp",
  },
  {
    firstname: "Michael",
    lastname: "Curiger",
    primaryFunction: "Soldat",
    secondaryFunctions: "-",
    joined: "2022",
    imagePath: "/images/persons/michael-curiger.webp",
  },
  {
    firstname: "Daniel",
    lastname: "Vuichard",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Phillip",
    lastname: "Freimann",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Antony",
    lastname: "Brun",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Claudio",
    lastname: "Passofaro",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Daniel",
    lastname: "Bishop",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Daniel",
    lastname: "Hess",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "David",
    lastname: "Alpstäg",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Lars",
    lastname: "Camenzind",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Martin",
    lastname: "Ulrich",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Martina",
    lastname: "Schüle",
    primaryFunction: "Wachtmeister",
    secondaryFunctions:
      "Atemschutz, Chemiewehr, FUST, Techzug, Jugendfeuerwehr-Kader",
    joined: "2019",
    imagePath: "/images/persons/martina-schüle.webp",
  },
  {
    firstname: "Matthias",
    lastname: "Wipfli",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Sophia",
    lastname: "Nash",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
  {
    firstname: "Thomas",
    lastname: "Freimann",
    primaryFunction: "-",
    secondaryFunctions: "-",
    joined: "",
    imagePath: "",
  },
];
